
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler.sintactico;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int DISTINTO = 27;
  public static final int STRING_LITERAL = 47;
  public static final int PR_FIBONACCI = 23;
  public static final int MULT = 32;
  public static final int PR_BREAK = 8;
  public static final int PR_INPUT_INT = 19;
  public static final int ENTERO = 44;
  public static final int PR_INTEGER = 15;
  public static final int DOS_PUNTOS = 38;
  public static final int PR_ELSE = 12;
  public static final int MENOS_UNARIO = 34;
  public static final int IDENTIFICADOR = 48;
  public static final int NOT = 42;
  public static final int AND = 40;
  public static final int PR_FLOAT = 16;
  public static final int PR_INPUT_BOOL = 21;
  public static final int PR_THEN = 11;
  public static final int OR = 41;
  public static final int IGUALDAD = 26;
  public static final int DIV = 33;
  public static final int PR_BOOLEAN = 14;
  public static final int BOOLEAN = 46;
  public static final int DUPLE = 45;
  public static final int P_CIERRA = 37;
  public static final int EOF = 0;
  public static final int PR_UNLESS = 10;
  public static final int error = 1;
  public static final int COMA = 39;
  public static final int PR_INPUT_DUPLE = 22;
  public static final int PR_SHOW = 18;
  public static final int MENOS = 31;
  public static final int MENOR = 24;
  public static final int PR_CONTINUE = 9;
  public static final int PR_ENDPROGRAM_SECTION = 3;
  public static final int ASIGNACION = 35;
  public static final int MAYOR = 25;
  public static final int PR_END = 13;
  public static final int PR_ENDDECLARE_SECTION = 5;
  public static final int MAYOR_IGUAL = 29;
  public static final int FLOAT = 43;
  public static final int PR_PROGRAM_SECTION = 2;
  public static final int P_ABRE = 36;
  public static final int PR_INPUT_FLOAT = 20;
  public static final int MENOR_IGUAL = 28;
  public static final int PR_UNTIL = 7;
  public static final int PR_REPEAT = 6;
  public static final int PR_DECLARE_SECTION = 4;
  public static final int PR_DUPLE = 17;
  public static final int MAS = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PR_PROGRAM_SECTION",
  "PR_ENDPROGRAM_SECTION",
  "PR_DECLARE_SECTION",
  "PR_ENDDECLARE_SECTION",
  "PR_REPEAT",
  "PR_UNTIL",
  "PR_BREAK",
  "PR_CONTINUE",
  "PR_UNLESS",
  "PR_THEN",
  "PR_ELSE",
  "PR_END",
  "PR_BOOLEAN",
  "PR_INTEGER",
  "PR_FLOAT",
  "PR_DUPLE",
  "PR_SHOW",
  "PR_INPUT_INT",
  "PR_INPUT_FLOAT",
  "PR_INPUT_BOOL",
  "PR_INPUT_DUPLE",
  "PR_FIBONACCI",
  "MENOR",
  "MAYOR",
  "IGUALDAD",
  "DISTINTO",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "MAS",
  "MENOS",
  "MULT",
  "DIV",
  "MENOS_UNARIO",
  "ASIGNACION",
  "P_ABRE",
  "P_CIERRA",
  "DOS_PUNTOS",
  "COMA",
  "AND",
  "OR",
  "NOT",
  "FLOAT",
  "ENTERO",
  "DUPLE",
  "BOOLEAN",
  "STRING_LITERAL",
  "IDENTIFICADOR"
  };
}

